#!/bin/sh
SCRIPT=./grass.awk

case "$1" in
	(-v)
	awk -f $SCRIPT -v verbose=1 -v srcfile=$2
	;;
	(--)
	TMP=./grass.tmp.g
	cat > $TMP
	awk -f $SCRIPT -v srcfile=$TMP
	rm -f $TMP
	;;
	(*)
	awk -f $SCRIPT -v srcfile=$1
esac
